from django.forms import ModelForm
from application.models import medData

class MedDataForm(ModelForm):
    class Meta:
        model = medData
        fields = '__all__'
        labels = {
            "anonymousID": "votre ID",
            "date": "date",
            "poids": "Indiquez votre poids",
            "tourTaille": "Tour de taille en cm",
            "freqCard": "Fréquence cardiaque par minute ",
            "systMatin": "Tension artérielle systolique (prise du matin) ",
            "systSoir": "Tension artérielle systolique (prise du soir)",
            "diastMatin": "Tension artérielle diastolique (prise du matin)",
            "diastSoir": "Tension artérielle diastolique (prise du soir)",
            "symptCardio": "Décrivez vos symptomes cardiovasculaires en quelques mots (malaise, perte de connaissance…)",
            "nbMed": "Nombre de médicaments pris dans la journée",
            "oubliMatinYN": "Oubli de prendre le(s) médicament(s) le matin ",
            "oubliSoirYN": "Oubli de prendre le(s) médicament(s) le soir ",
            "effetSecYN": "Présence d'effets secondaires ",
            "symptomesYN": "Symptôme(s) particulier(s) remarqué(s) ",
            "effetSympt": "Décrivez vos effets secondaires et/ou symptomes particuliers remarqués en quelques mots",
            "alcoolYN": "Consommation d'alcool",
            "grignoSucreYN": "Grignotage sucré",
            "grignoSaleYN": "Grignotage salé",
            "nbRepas": "Nombre de repas pris durant la journée",
            "qqteEau": "Quantité d'eau bue en litre",
            "qqteAlcool": "Quantité d'alcool consommé en litre",
            "actPhysYN": "J'ai eu une activité physique aujourd'hui",
            "actPhys": "Décrivez la nature de votre activité physique",
            "dureeActPhys": "Durée de l'activité physique en minutes",
            "dyspneeYN": "Présence de dyspnée",
            "oedemeYN": "Présence d'œdème",
            "infectionYN": "Présence d'infection",
            "fievreYN": "Présence de fièvre",
            "palpitationYN": "Présence de palpitations",
            "douleurThoYN": "Présence de douleur thoracique",
            "malaiseYN": "Présence de malaise",
            "debutPalp": "Indiquez l'heure de début des palpitations",
            "durationPalp": "Indiquez la durée total des palpitations apparues durant la journée en minute",
            "debutDouleurTho": "Indiquez l'heure de début des douleurs thoraciques",
            "durationDouleurTho": "Indiquez la durée total des douleurs thoraciques apparues durant la journée en minute",
            "debutMalaise": "Indiquez l'heure de début des malaises",
            "durationMalaise": "Indiquez la durée total des malaises apparus durant la journée en minute",
            "irritab": "Irritabilité",
            "depression": "Sentiments dépressifs",
            "boucheSeche": "Bouche sèche ou gorge sèche",
            "gestesImpulsifs": "Actions ou gestes impulsifs",
            "grincementDents": "Grincement des dents",
            "difficulteAssis": "Difficulté à rester assis",
            "cauchemars": "Cauchemars",
            "diarrhee": "Diarrhée",
            "attaqueVerb": "Attaques verbales envers quelqu’un",
            "hautBasEmot": "Hauts et bas émotifs",
            "enviePleurer": "Grande envie de pleurer",
            "envieFuir": "Grande envie de fuir",
            "envieFaireMal": "Grande envie de faire mal",
            "penseeEmbr": "Pensées embrouillées",
            "debitRapide": "Débit plus rapide",
            "fatigue": "Fatigue ou lourdeur généralisées",
            "sentimentSurcharge": "Sentiment d’être surchargé(e)",
            "sentimentFragile": "Sentiment d’être émotivement fragile",
            "sentimentTristesse": "Sentiment de tristesse",
            "sentimentAnxiete": "Sentiment d’anxiété",
            "tensionEmot": "Tension émotionnelle",
            "hostilite": "Hostilité envers les autres",
            "tremblements": "Tremblements ou gestes nerveux",
            "begaiements": "Bégaiements ou hésitations verbales",
            "diffConcentrer": "Incapacité ou difficulté à se concentrer",
            "diffPensee": "Difficulté à organiser ses pensées",
            "diffDormir": "Difficulté à dormir toute la nuit sans se réveiller",
            "besoinUriner": "Besoin fréquent d’uriner",
            "mauxEstomac": "Maux d’estomac ou difficultés à digérer",
            "impatience": "Geste ou sentiment d’impatience",
            "mauxTete": "Maux de tête",
            "douleurDos": "Douleurs au dos ou à la nuque",
            "appetit": "Perte ou gain d’appétit",
            "sexe": "Perte d’intérêt pour le sexe",
            "oublis": "Oublis fréquents",
            "douleurPoitrine": "Douleurs ou serrements à la poitrine",
            "conflits": "Conflits significatifs avec les autres",
            "diffLever": "Difficulté à se lever après le sommeil",
            "sentimentHorsCtrl": "Sentiment que les choses sont hors de contrôle",
            "diffActivite": "Difficulté à faire une longue activité continue",
            "retrait": "Mouvements de retrait, d’isolement",
            "diffEndormir": "Difficulté à s'endormir",
            "diffRemettreEvent": "Difficulté à se remettre d’un événement contrariant",
            "mainsMoites": "Mains moites"
            # Define custom labels for other fields as needed
        }