# Generated by Django 4.2.5 on 2023-09-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="medData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                ("symptCardio", models.CharField(max_length=100)),
                (
                    "oubliMatinYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                (
                    "oubliSoirYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                (
                    "effetSecYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                (
                    "symptomesYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                ("effetSympt", models.CharField(max_length=100)),
                (
                    "grignoSucreYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                (
                    "grignoSaleYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                (
                    "actPhysYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                ("actPhys", models.CharField(max_length=100)),
                (
                    "dyspneeYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                (
                    "oedemeYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                (
                    "infectionYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                (
                    "fievreYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                (
                    "palpitationYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                (
                    "douleurThoYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                (
                    "malaiseYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
            ],
        ),
    ]
