# Generated by Django 4.2.5 on 2023-09-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="medData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anonymousID", models.CharField(max_length=50)),
                ("date", models.DateField(auto_now=True)),
                ("poids", models.DecimalField(decimal_places=2, max_digits=6)),
                ("freqCard", models.IntegerField()),
                ("systMatin", models.IntegerField()),
                ("systSoir", models.IntegerField()),
                ("diastMatin", models.IntegerField()),
                ("diastSoir", models.IntegerField()),
                ("symptCardio", models.CharField(max_length=100)),
                ("nbMed", models.IntegerField()),
                (
                    "oubliMatinYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                (
                    "oubliSoirYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                (
                    "effetSecYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                (
                    "symptomesYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                ("effetSympt", models.CharField(max_length=100)),
                (
                    "alcoolYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                (
                    "grignoSucreYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                (
                    "grignoSaleYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                ("nbRepas", models.IntegerField()),
                ("qqteEau", models.DecimalField(decimal_places=2, max_digits=6)),
                ("qqteAlcool", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "actPhysYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                ("actPhys", models.CharField(max_length=100)),
                ("dureeActPhys", models.IntegerField()),
                (
                    "dyspneeYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                (
                    "oedemeYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                (
                    "infectionYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                (
                    "fievreYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                (
                    "palpitationYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                (
                    "douleurThoYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                (
                    "malaiseYN",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=3
                    ),
                ),
                ("debutPalp", models.DateField()),
                ("durationPalp", models.DurationField()),
                ("debutDouleurTho", models.DateField()),
                ("durationDouleurTho", models.DurationField()),
                ("debutMalaise", models.DateField()),
                ("durationMalaise", models.DurationField()),
                (
                    "irritab",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "depression",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "boucheSeche",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "gestesImpulsifs",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "grincementDents",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "difficulteAssis",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "cauchemars",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "diarrhee",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "attaqueVerb",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "hautBasEmot",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "enviePleurer",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "envieFuir",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "envieFaireMal",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "penseeEmbr",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "debitRapide",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "fatigue",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "sentimentSurcharge",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "sentimentFragile",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "sentimentTristesse",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "sentimentAnxiete",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "tensionEmot",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "hostilite",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "tremblements",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "begaiements",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "diffConcentrer",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "diffPensee",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "diffDormir",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "besoinUriner",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "mauxEstomac",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "impatience",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "mauxTete",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "douleurDos",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "appetit",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "sexe",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "oublis",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "douleurPoitrine",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "conflits",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "diffLever",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "sentimentHorsCtrl",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "diffActivite",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "retrait",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "diffEndormir",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "diffRemettreEvent",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
                (
                    "mainsMoites",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (5, "5"), (10, "10")], default=0
                    ),
                ),
            ],
        ),
    ]
