# Generated by Django 4.2.5 on 2023-09-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meddata",
            name="actPhysYN",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="alcoolYN",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="douleurThoYN",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="dyspneeYN",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="effetSecYN",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="fievreYN",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="grignoSaleYN",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="grignoSucreYN",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="infectionYN",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="malaiseYN",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="oedemeYN",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="oubliMatinYN",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="oubliSoirYN",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="palpitationYN",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="symptomesYN",
            field=models.BooleanField(default=False),
        ),
    ]
