# Generated by Django 4.2.5 on 2023-09-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_alter_meddata_actphysyn_alter_meddata_alcoolyn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meddata",
            name="debutDouleurTho",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="debutMalaise",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="debutPalp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
