# Generated by Django 4.2.5 on 2023-09-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0004_alter_meddata_debutdouleurtho_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meddata",
            name="actPhys",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="debutDouleurTho",
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="debutMalaise",
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="debutPalp",
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="durationDouleurTho",
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="durationMalaise",
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="durationPalp",
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="dureeActPhys",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="effetSympt",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="symptCardio",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
