# Generated by Django 4.2.5 on 2023-09-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "application",
            "0005_alter_meddata_actphys_alter_meddata_debutdouleurtho_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="meddata",
            name="debutDouleurTho",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="debutMalaise",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="meddata",
            name="debutPalp",
            field=models.TimeField(null=True),
        ),
    ]
